/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pymrzxepvufczgeeauwf";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bXJ6eGVwdnVmY3pnZWVhdXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMzE4MDgsImV4cCI6MjA4NDYwNzgwOH0.UQzeIdDsaRmabZuUevxBjCuhg2UKn1pIVi5utaqH0MQ";
